VR Initial setup for experiment 5
emotional-cities/walker-experiments pull request #45
Opened 2023-10-12 10:19 UTC by aspaNeuro

This PR adds a new unity project to this repo, VR-Alfama.
Data collected on this Experiment is sent to Bonsai and logged same way and principle that was being done for the outdoor experiments.
A new acquisition workflow for the VR experiment is included in this PR.
A new set of code files to deal with Glia and VR Experiments Data streams on the bonsai side is also included, maybe they should promoted to another repo for ease of reuse.
Logging of all streams in the experimental Workflow for the VR experiment.
All Unity assets are in a shared folder in Sharepoint.
Fixes #44

2023-10-16 08:44 UTC, RoboDoig commented
I just noticed as well that there are a number of data files from the benchmarking experiments (e.g. for Lsl jitter test). Do we want to include these or rather leave a reference to a cloud storage area?

2023-10-16 12:50 UTC, glopesdev commented
@RoboDoig I would move all data outside of the repository, yes. We don't even need to keep a reference in the repository specifically unless it is needed to run something inside?

2023-10-19 10:11 UTC, glopesdev requested changes
I was thinking and probably might make sense to do as much of the folder and environment restructuring in this PR as possible. That would allow us to cleanup all the git history, including removal of binary files etc, in this branch and then merge a fully cleaned up history.

Below some comments to improve, but probably will need another pass after this.

2023-10-19 10:11 UTC, glopesdev commented on .gitignore
> +/*/*/Packages
Consider whether we still need the relative-path folder given that the more general `Packages` is still in .gitignore. If files are already committed in ignored folders they will still be actively tracked by git (only new ones will not show up).

2023-10-19 10:11 UTC, glopesdev commented on .gitignore
> +Data
New line could be removed but we can review this at the end.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/.idea/LslJitterExperiment.iml
JetBrains IDEA files should potentially be ignored / removed from branch before merging PR.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/.idea/modules.xml
JetBrains IDEA files should potentially be ignored / removed from branch before merging PR.

2023-10-19 10:11 UTC, glopesdev commented on .gitignore
>  *.blend
```suggestion
.idea
*.blend
```

2023-10-19 10:11 UTC, glopesdev commented on .gitignore
>  *.blend
Add JetBrains IDEA files to gitignore.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/.idea/workspace.xml
JetBrains IDEA files should potentially be ignored / removed from branch before merging PR.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/BidirectionalJitterTest/ProcAll/Machine1_ReceivedStream1.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/BidirectionalJitterTest/ProcAll/Machine1_ReceivedStream2.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/BidirectionalJitterTest/ProcAll/Machine2_ReceivedStream1.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/BidirectionalJitterTest/ProcAll/Machine2_ReceivedStream2.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/BidirectionalJitterTest/ProcClksync/Machine1_ReceivedStream1.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/BidirectionalJitterTest/ProcClksync/Machine1_ReceivedStream2.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/BidirectionalJitterTest/ProcClksync/Machine2_ReceivedStream1.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/BidirectionalJitterTest/ProcClksync/Machine2_ReceivedStream2.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/BidirectionalJitterTest/ProcNone/Machine1_ReceivedStream1.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/BidirectionalJitterTest/ProcNone/Machine1_ReceivedStream2.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/BidirectionalJitterTest/ProcNone/Machine2_ReceivedStream1.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/BidirectionalJitterTest/ProcNone/Machine2_ReceivedStream2.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/JitterTest/received-timestamps-proc-all.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/JitterTest/received-timestamps-proc-clksync.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Analysis/JitterTest/received-timestamps-proc-none.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Bonsai/Bonsai.config
Ideally this environment should be merged with the top-level environment. Can be postponed to a later PR if it is too complicated to do now.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Bonsai/NuGet.config
Ideally this environment should be merged with the top-level environment. Can be postponed to a later PR if it is too complicated to do now.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Bonsai/Setup.cmd
Ideally this environment should be merged with the top-level environment. Can be postponed to a later PR if it is too complicated to do now.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Bonsai/Setup.ps1
Ideally this environment should be merged with the top-level environment. Can be postponed to a later PR if it is too complicated to do now.

2023-10-19 10:11 UTC, glopesdev commented on LslJitterExperiment/Bonsai/lsl.dll
After merging with the top-level environment we can review whether this file is still needed.

2023-10-19 10:11 UTC, glopesdev commented on VR-Alfama/Assets/GoogleMaps/ReferenceImage.png
Do we need this reference image or can it be made part of the cloud assets as well?

2023-10-19 10:11 UTC, glopesdev commented on VR-Alfama/Assets/GoogleMaps/ReferenceImage.png.meta
Related to the above.

2023-10-19 10:11 UTC, glopesdev commented on Workflows/Extensions/ZeroMQMessageToByteArray.cs
Do we still need this given the new ZMQ operators? Maybe there is a way to do this with the new version of the package?

2023-10-19 10:11 UTC, glopesdev commented on VR-Alfama/Assets/HDRPDefaultResources/DefaultHDRPAsset 1.asset
Check if space in filename might be a problem in the future.

2023-10-19 10:11 UTC, glopesdev commented on VR-Alfama/Assets/HDRPDefaultResources/DefaultLookDevProfile 1.asset
Check if space in filename might be a problem in the future.

2023-10-19 10:11 UTC, glopesdev commented on VR-Alfama/Assets/HDRPDefaultResources/DefaultLookDevProfile 1.asset.meta
Check if space in filename might be a problem in the future.

2023-10-19 10:11 UTC, glopesdev commented on VR-Alfama/Assets/Workflows/harp-sync-test.bonsai
Are we still using this workflow?

2023-10-19 10:11 UTC, glopesdev commented on VR-Alfama/Assets/Workflows/osc-receiver.bonsai
Are we using OSC to send messages from Bonsai to Unity or just ZMQ?

2023-10-19 10:11 UTC, glopesdev commented on VR-Alfama/Packages/manifest.json
> +    "com.neurogears.pluma-vr": "file:C:/git/emotional-cities/pluma-vr/com.neurogears.plumavr",
Check if this absolute file path reference can be replaced with a relative path.

2023-10-19 10:11 UTC, glopesdev commented on VR-Alfama/Packages/packages-lock.json
> +      "version": "file:C:/git/emotional-cities/pluma-vr/com.neurogears.plumavr",
This file might have to be regenerated after changing the relative reference path above.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/.idea/VRLatencyExperiment.iml
JetBrains IDEA files should potentially be ignored / removed from branch before merging PR.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/.idea/modules.xml
JetBrains IDEA files should potentially be ignored / removed from branch before merging PR.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Analysis/Data230227/round-trip-timestamps-diffs.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Analysis/Data230227/round-trip-timestamps.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Analysis/Data230227/switch-times-3.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Analysis/Data230227/switch-times-unity-3.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Analysis/Data230227/switch-times-unity.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Analysis/Data230227/switch-times.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Analysis/Data230327/headset-stream.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Analysis/Data230327/screen-stream.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Analysis/headset-stream.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Analysis/screen-stream.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Analysis/zmq-events.csv
Move data files to cloud storage `Datasets\Benchmarks` folder under experiment control.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Bonsai/Bonsai.config
Ideally this environment should be merged with the top-level environment. Can be postponed to a later PR if it is too complicated to do now.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Bonsai/NuGet.config
Ideally this environment should be merged with the top-level environment. Can be postponed to a later PR if it is too complicated to do now.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Bonsai/Setup.cmd
Ideally this environment should be merged with the top-level environment. Can be postponed to a later PR if it is too complicated to do now.

2023-10-19 10:11 UTC, glopesdev commented on VRLatencyExperiment/Bonsai/Setup.ps1
Ideally this environment should be merged with the top-level environment. Can be postponed to a later PR if it is too complicated to do now.

2023-10-19 10:11 UTC, glopesdev commented on Workflows/Extensions/ZeroMQLogging.bonsai
> +          <dsp:Path>C:\IndoorData\NGR_LAB_sub-01_2023-10-11T222512Z\\StreamReadDump.bin</dsp:Path>
Remove absolute path from included workflow.

2023-10-19 10:11 UTC, glopesdev commented on Workflows/Extensions/ToOmniceptMouthCamera.cs
> +[Description("Convert Glia mouth camera ZeroMQ messages into bonsai compliant data structures")]
Remove references to bonsai in the description, usually we would prefer simply something like "Parses a sequence of ZeroMQ messages into Glia mouth camera objects".

2023-10-19 10:11 UTC, glopesdev commented on Workflows/Extensions/ToOmniceptIMU.cs
> +[Description("Convert Glia Eye ZeroMQ messages into bonsai compliant data structures")]
See comment above.

2023-10-19 10:11 UTC, glopesdev commented on Workflows/Extensions/ToOmniceptHeartRate.cs
> +[Description("Convert Glia heart rate ZeroMQ messages into bonsai compliant data structures")]
See above comments.

2023-10-19 10:11 UTC, glopesdev commented on Workflows/Extensions/ToOmniceptEyeTracking.cs
> +[Description("Convert Glia Eye ZeroMQ messages into bonsai compliant data structures")]
See above comments.

2023-10-19 10:11 UTC, glopesdev commented on Workflows/Extensions/StringToInt.cs
> +public class StringToInt
Consider a more suggestive name and description. Looks like this is more of a lookup for a specified array of strings? Maybe `LookupStringIndex` and maybe if there is a defined meaning for these trings, e.g. if they are topics you could even make it more concrete like `LookupTopicIndex`.

2023-10-19 10:11 UTC, glopesdev commented on Workflows/Extensions/StringToInt.cs
> +    public string[] Topic{ get; set;}
Since this is a collection of strings, the plural form is usually recommended, so `Topics` instead of `Topic`.

2023-10-19 10:11 UTC, glopesdev commented on Workflows/ExperimentAcquisitionVR.bonsai
> +                    <io:FileName>C:\IndoorData\NGR_LAB_sub-01_2023-10-12T164616Z\\Accelerometer.csv</io:FileName>
Consider removing absolute paths from workflow files. The usual approach to do this is to rely on include workflows and subjects, which will pass the data without saving it to the workflow (i.e. the path remains internal to the included workflow instance but the saved included workflow file does not need to change).

2023-10-19 13:24 UTC, aspaNeuro commented on .gitignore
>  *.blend
Agree

2023-10-19 13:27 UTC, aspaNeuro commented on VR-Alfama/Assets/GoogleMaps/ReferenceImage.png
That image needs to be removed, @jfrazao noted in the other day that we cannot use google maps images whatsoever...

2023-10-20 08:49 UTC, aspaNeuro commented on VR-Alfama/Assets/HDRPDefaultResources/DefaultHDRPAsset 1.asset
This is a downloaded package so we should keep it as is

2023-10-23 08:30 UTC, aspaNeuro commented on Workflows/Extensions/ZeroMQMessageToByteArray.cs
The trick is that ZeroMQMessageToByteArray adds a '\0' ate the end of the string that is the topic in frame 1 of the ZeroMQ message, Which is required for you to be able to parse different topics form the same generated byte array.

2023-10-23 08:31 UTC, aspaNeuro commented on VR-Alfama/Assets/HDRPDefaultResources/DefaultLookDevProfile 1.asset
This is a downloaded package so we where trying to keep it as is...

2023-10-23 08:46 UTC, aspaNeuro commented on VR-Alfama/Assets/Workflows/osc-receiver.bonsai
Just ZeroMQ OSC was used as a benchmark only.

2023-11-30 11:37 UTC, glopesdev commented on Workflows/Extensions/StringToInt.cs
Following further discussions, this is actually a step in assigning a base address for Harp message logging based on a known list of topics. In that case, we could consider directly adding the base address as a property in this operator and call it something like `GetTopicHarpAddress`.

2024-04-02 10:38 UTC, closed without merging